function getField(block, name, fallback = '') {
  const field = block.querySelector(`[data-aue-prop="${name}"]`);

  if (field) return field.textContent.trim() || field.dataset.value || fallback;

  return block.dataset[name] || fallback;
}

function getBoolean(block, name, fallback = false) {
  const value = getField(block, name, String(fallback)).toLowerCase();

  return value === 'true' || value === 'yes' || value === '1';
}

function slugify(value) {
  return `/${value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
}

function getNavigationLinks(block) {
  const links = [];

  // Parse multi-field inputs generated by Universal Editor for label and link
  const labelNodes = [...block.querySelectorAll('[data-aue-prop="label"]')];
  const linkNodes = [...block.querySelectorAll('[data-aue-prop="link"]')];

  const labels = labelNodes.map((node) => node.textContent.trim() || node.dataset.value || '').filter(Boolean);
  const hrefs = linkNodes.map((node) => node.textContent.trim() || node.dataset.value || '').filter(Boolean);

  // Pair up multi-field labels and links by index
  if (labels.length || hrefs.length) {
    const maxLength = Math.max(labels.length, hrefs.length);

    for (let i = 0; i < maxLength; i += 1) {
      const text = labels[i] || hrefs[i] || `Link ${i + 1}`;
      const href = hrefs[i] || slugify(text);

      links.push({ text, href });
    }

    return links;
  }

  // Fallback if authored via nested DOM container wrappers
  const container = block.querySelector('[data-aue-prop="navigationItems"]');

  if (container) {
    const itemElements = container.children.length > 0
      ? Array.from(container.children)
      : [container];

    itemElements.forEach((item) => {
      const labelEl = item.querySelector('[data-aue-prop="label"]') || item;
      const linkEl = item.querySelector('[data-aue-prop="link"]');

      const text = labelEl.textContent.trim() || labelEl.dataset.value || '';
      const href = linkEl?.textContent.trim() || linkEl?.dataset.value || slugify(text);

      if (text) {
        links.push({ text, href });
      }
    });

    if (links.length > 0) return links;
  }

  // Fallback for standard Edge Delivery table rows (div > div)
  const rows = [...block.children];
  rows.forEach((row) => {
    const cols = [...row.children];
    if (cols.length >= 2) {
      const labelText = cols[0].textContent.trim();
      const linkText = cols[1].textContent.trim() || cols[1].querySelector('a')?.getAttribute('href') || slugify(labelText);

      if (labelText) {
        links.push({ text: labelText, href: linkText });
      }
    }
  });

  return links;
}

function createLink(href, text, className = '') {
  const link = document.createElement('a');

  link.href = href;
  link.textContent = text;

  if (className) link.className = className;

  return link;
}

export default function decorate(block) {
  // Extract values from the authored DOM BEFORE clearing block content
  const variant = getField(block, 'headerVariant', 'standard').toLowerCase();
  const brandName = getField(block, 'brandName', 'Brand');
  const brandLink = getField(block, 'brandLink', '/');
  const brandLogo = getField(block, 'brandLogo');
  const ctaText = getField(block, 'ctaText');
  const ctaLink = getField(block, 'ctaLink');
  const showSearch = getBoolean(block, 'showSearch', true);
  const navigationLinks = getNavigationLinks(block);

  // Apply variant modifier class
  if (variant !== 'standard') block.classList.add(variant);

  // Clear original authored DOM content
  block.textContent = '';

  const nav = document.createElement('nav');

  nav.className = 'dummy-header-nav';
  nav.setAttribute('aria-label', 'Primary navigation');

  // 1. Render Brand Section
  const brandSection = document.createElement('div');

  brandSection.className = 'dummy-header-brand';

  const brand = createLink(brandLink, brandName, 'dummy-header-brand-link');

  if (brandLogo) {
    const logo = document.createElement('img');

    logo.src = brandLogo;
    logo.alt = brandName;

    brand.replaceChildren(logo, document.createTextNode(brandName));
  }

  brandSection.append(brand);

  // 2. Render Navigation Items
  const sections = document.createElement('div');

  sections.className = 'dummy-header-sections';

  const navigation = document.createElement('ul');

  navigationLinks.forEach(({ href, text }) => {
    const item = document.createElement('li');

    item.append(createLink(href, text));
    navigation.append(item);
  });

  sections.append(navigation);

  // 3. Render Tools Section
  const tools = document.createElement('div');

  tools.className = 'dummy-header-tools';

  if (showSearch) {
    const search = createLink('/search', 'Search', 'dummy-header-search');

    search.setAttribute('aria-label', 'Search');
    tools.append(search);
  }

  if (ctaText && ctaLink) {
    tools.append(createLink(ctaLink, ctaText, 'dummy-header-cta'));
  }

  nav.append(brandSection, sections, tools);

  block.append(nav);
}
